export const DATA_PHONES = [
    { brand: "Apple", model: ["iPhone 14", "iPhone 14 Pro", "iPhone 14 Pro Max", "iPhone 14 Mini", "iPhone 13", "iPhone 13 Pro", "iPhone 13 Pro Max", "iPhone 13 Mini", "iPhone 12", "iPhone 12 Pro", "iPhone 12 Pro Max", "iPhone 12 Mini", "iPhone SE (2020)", "iPhone SE (2022)", "iPhone 11", "iPhone 11 Pro", "iPhone 11 Pro Max"] },
    { brand: "Samsung", model: ["Galaxy S23", "Galaxy S23+", "Galaxy S23 Ultra", "Galaxy S22", "Galaxy S22+", "Galaxy S22 Ultra", "Galaxy Note 20", "Galaxy Note 20 Ultra", "Galaxy Z Fold4", "Galaxy Z Flip4", "Galaxy A73", "Galaxy A53", "Galaxy A33", "Galaxy M53", "Galaxy M33", "Galaxy M23"] },
    { brand: "Huawei", model: ["P50", "P50 Pro", "P50 Pocket", "Mate 50", "Mate 50 Pro", "Nova 9", "Nova 8", "Y9a", "Y7a", "Mate Xs 2"] },
    { brand: "Xiaomi", model: ["Mi 13", "Mi 13 Pro", "Mi 13 Ultra", "Redmi Note 12", "Poco X5 Pro", "Poco X5", "Mi 12", "Mi 12 Pro", "Mi 12 Ultra", "Black Shark series"] },
    { brand: "Oppo", model: ["Find X5", "Find X5 Pro", "Reno 8", "A96", "A77", "F21 Pro"] },
    { brand: "Vivo", model: ["X80", "X80 Pro", "V23", "Y75", "Y21", "iQOO series"] },
    { brand: "OnePlus", model: ["OnePlus 11", "OnePlus 11 Pro", "OnePlus 10 Pro", "OnePlus 10T", "OnePlus Nord 2", "OnePlus Nord CE 2", "OnePlus 9", "OnePlus 9 Pro"] },
    { brand: "Google (Pixel)" , model: ["Pixel 7", "Pixel 7 Pro", "Pixel 6", "Pixel 6 Pro", "Pixel 6a", "Pixel 5", "Pixel 5a", "Pixel 4", "Pixel 4a", "Pixel 4 XL"] },
    { brand: "Motorola", model: ["Moto G Stylus 2023", "Moto G Power 2023", "Moto E22", "Moto E32", "Moto Edge 40", "Moto Edge 40 Pro", "Razr 2023"] },
    { brand: "Sony", model: ["Xperia 1 V", "Xperia 1 IV", "Xperia 5 V", "Xperia 5 IV", "Xperia 10 V", "Xperia 10 IV", "Xperia Pro-I"] },
    { brand: "Nokia", model: ["Nokia XR20", "Nokia G50", "Nokia G21", "Nokia C30", "Nokia C20", "Nokia 8.3 5G"] },
    { brand: "LG", model: ["LG Wing", "LG Velvet", "LG V60 ThinQ", "LG G8X ThinQ"] },
    { brand: "Realme", model: ["Realme GT 2", "Realme GT 2 Pro", "Realme 9", "Realme 9 Pro+", "Realme Narzo 50", "Realme C35", "Realme C31"] },
    { brand: "Asus", model: ["ROG Phone 7", "ROG Phone 7 Ultimate", "Zenfone 9", "Zenfone 8"] },
    { brand: "ZTE", model: ["Axon 40 Ultra", "Axon 30", "Blade V30"] },
    { brand: "TCL", model: ["TCL 30", "TCL 30+", "TCL 20", "TCL 10"] },
    { brand: "Lenovo", model: ["Lenovo Legion Phone Duel 2", "Lenovo K12"] },
    { brand: "Honor", model: ["Honor Magic4", "Honor Magic4 Pro", "Honor 70"] },
    { brand: "Alcatel", model: ["Alcatel 1", "Alcatel 1B", "Alcatel 3L", "Alcatel 5V"] },
    { brand: "Meizu", model: ["Meizu 18s Pro", "Meizu 17"] },
    { brand: "Tecno", model: ["Phantom X2", "Camon 19", "Spark 8"] },
    { brand: "Infinix", model: ["Zero Ultra", "Note 12", "Hot 12"] },
    { brand: "Lava", model: ["Lava Z6", "Lava Z2 Max"] },
    { brand: "Micromax", model: ["Micromax IN Note 2", "Micromax IN 2b"] },
    { brand: "Fairphone", model: ["Fairphone 4", "Fairphone 3+"] },
    { brand: "Energizer", model: ["Energizer Power Max P18K Pop", "Energizer Hardcase H570S"] },
    { brand: "BlackBerry", model: ["BlackBerry Key2", "BlackBerry Key2 LE"] },
];
